[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PORT = "8080" 